"""empty message

Revision ID: 1544c1b1f7e2
Revises: 
Create Date: 2020-06-09 22:19:01.580647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1544c1b1f7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('senha', sa.String(length=10), nullable=False),
    sa.Column('telefone', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('senha'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('tbClientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbProduto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('venda', sa.Float(), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('validade', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbVendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataVenda', sa.String(length=20), nullable=True),
    sa.Column('dataEntrega', sa.String(length=20), nullable=True),
    sa.Column('pagamento', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('valorVenda', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['tbClientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['tbProduto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbVendas')
    op.drop_table('tbProduto')
    op.drop_table('tbClientes')
    op.drop_table('users')
    # ### end Alembic commands ###
